create table if not exists tenants (
    id bigint generated by default as identity primary key,
    code varchar(80) not null unique,
    name varchar(150) not null,
    status varchar(30) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null
);

create table if not exists roles (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    name varchar(120) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null
);

create table if not exists app_users (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    role_id bigint not null,
    email varchar(180) not null unique,
    full_name varchar(180) not null,
    google_subject varchar(180),
    picture_url varchar(512),
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null,
    constraint fk_app_users_tenant foreign key (tenant_id) references tenants (id),
    constraint fk_app_users_role foreign key (role_id) references roles (id)
);

create table if not exists stores (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    code varchar(80) not null,
    name varchar(180) not null,
    type varchar(30) not null,
    status varchar(30) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null,
    constraint fk_stores_tenant foreign key (tenant_id) references tenants (id),
    constraint uk_stores_tenant_code unique (tenant_id, code)
);

create table if not exists store_users (
    id bigint generated by default as identity primary key,
    store_id bigint not null,
    user_id bigint not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null,
    constraint fk_store_users_store foreign key (store_id) references stores (id),
    constraint fk_store_users_user foreign key (user_id) references app_users (id),
    constraint uk_store_users_store_user unique (store_id, user_id)
);

create table if not exists commission_rules (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    store_id bigint,
    name varchar(150) not null,
    scope varchar(30) not null,
    type varchar(30) not null,
    commission_value numeric(19,4) not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null,
    constraint fk_commission_rules_tenant foreign key (tenant_id) references tenants (id),
    constraint fk_commission_rules_store foreign key (store_id) references stores (id)
);

create table if not exists app_settings (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    setting_key varchar(120) not null,
    setting_value varchar(4000) not null,
    value_type varchar(30) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null,
    constraint fk_app_settings_tenant foreign key (tenant_id) references tenants (id),
    constraint uk_app_settings_tenant_key unique (tenant_id, setting_key)
);

create table if not exists products (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    store_id bigint not null,
    name varchar(180) not null,
    sku varchar(80) not null,
    description varchar(1024),
    sale_price numeric(19,4) not null,
    cost numeric(19,4),
    stock integer not null,
    status varchar(30) not null,
    barcode varchar(64) not null unique,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null,
    constraint fk_products_tenant foreign key (tenant_id) references tenants (id),
    constraint fk_products_store foreign key (store_id) references stores (id),
    constraint uk_products_store_sku unique (store_id, sku)
);

create table if not exists product_promotions (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    store_id bigint not null,
    product_id bigint not null,
    name varchar(180) not null,
    type varchar(30) not null,
    block_quantity integer not null,
    block_price numeric(19,4) not null,
    active boolean not null,
    starts_at timestamp with time zone,
    ends_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null,
    constraint fk_product_promotions_tenant foreign key (tenant_id) references tenants (id),
    constraint fk_product_promotions_store foreign key (store_id) references stores (id),
    constraint fk_product_promotions_product foreign key (product_id) references products (id)
);

create table if not exists uf_daily_values (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    effective_date date not null,
    uf_value numeric(19,4) not null,
    source varchar(120),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null,
    constraint fk_uf_daily_values_tenant foreign key (tenant_id) references tenants (id),
    constraint uk_uf_daily_values_tenant_date unique (tenant_id, effective_date)
);

create table if not exists sales (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    sale_number varchar(80) not null unique,
    status varchar(30) not null,
    payment_method varchar(30) not null,
    subtotal_amount numeric(19,4) not null,
    total_discount_amount numeric(19,4) not null,
    total_amount numeric(19,4) not null,
    total_commission_amount numeric(19,4) not null,
    total_net_amount numeric(19,4) not null,
    uf_value numeric(19,4),
    opened_at timestamp with time zone not null,
    confirmed_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null,
    constraint fk_sales_tenant foreign key (tenant_id) references tenants (id)
);

create table if not exists sale_items (
    id bigint generated by default as identity primary key,
    sale_id bigint not null,
    product_id bigint not null,
    store_id bigint not null,
    product_name_snapshot varchar(180) not null,
    product_sku_snapshot varchar(80) not null,
    product_barcode_snapshot varchar(64) not null,
    quantity integer not null,
    base_unit_price numeric(19,4) not null,
    line_base_subtotal numeric(19,4) not null,
    promotion_discount_amount numeric(19,4) not null,
    subtotal numeric(19,4) not null,
    pricing_type varchar(30) not null,
    applied_promotion_id bigint,
    applied_promotion_name varchar(180),
    commission1_amount numeric(19,4) not null,
    commission2_amount numeric(19,4) not null,
    commission_vat_amount numeric(19,4) not null,
    total_commission_amount numeric(19,4) not null,
    net_amount numeric(19,4) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null,
    constraint fk_sale_items_sale foreign key (sale_id) references sales (id),
    constraint fk_sale_items_product foreign key (product_id) references products (id),
    constraint fk_sale_items_store foreign key (store_id) references stores (id)
);

create table if not exists sale_store_summaries (
    id bigint generated by default as identity primary key,
    sale_id bigint not null,
    store_id bigint not null,
    line_count integer not null,
    unit_count integer not null,
    subtotal_amount numeric(19,4) not null,
    commission1_amount numeric(19,4) not null,
    commission2_amount numeric(19,4) not null,
    commission_vat_amount numeric(19,4) not null,
    total_commission_amount numeric(19,4) not null,
    net_amount numeric(19,4) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null,
    constraint fk_sale_store_summaries_sale foreign key (sale_id) references sales (id),
    constraint fk_sale_store_summaries_store foreign key (store_id) references stores (id),
    constraint uk_sale_store_summaries_sale_store unique (sale_id, store_id)
);

create table if not exists stock_movements (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    product_id bigint not null,
    store_id bigint not null,
    type varchar(30) not null,
    quantity integer not null,
    previous_stock integer not null,
    new_stock integer not null,
    reference_type varchar(60),
    reference_id bigint,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    version bigint not null,
    constraint fk_stock_movements_tenant foreign key (tenant_id) references tenants (id),
    constraint fk_stock_movements_product foreign key (product_id) references products (id),
    constraint fk_stock_movements_store foreign key (store_id) references stores (id)
);

create index if not exists idx_app_users_tenant on app_users (tenant_id);
create index if not exists idx_stores_tenant on stores (tenant_id);
create index if not exists idx_products_store on products (store_id);
create index if not exists idx_products_name on products (name);
create index if not exists idx_products_barcode on products (barcode);
create index if not exists idx_products_sku on products (sku);
create index if not exists idx_product_promotions_product on product_promotions (product_id);
create index if not exists idx_sales_tenant on sales (tenant_id);
create index if not exists idx_sale_items_sale on sale_items (sale_id);
create index if not exists idx_sale_items_store on sale_items (store_id);
create index if not exists idx_sale_store_summaries_store on sale_store_summaries (store_id);
create index if not exists idx_stock_movements_product on stock_movements (product_id);
