alter table sale_items
    alter column product_id drop not null;

alter table sale_items
    add column if not exists manual_entry boolean not null default false;

alter table sale_items
    add column if not exists manual_reference varchar(120);

create table if not exists pickups (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    tenant_id bigint not null,
    market_id bigint not null,
    store_id bigint not null,
    linked_sale_id bigint null,
    pickup_number varchar(80) not null,
    customer_name varchar(180) not null,
    description varchar(500) not null,
    payable boolean not null,
    amount_due numeric(19,4),
    status varchar(30) not null,
    collected_at timestamp with time zone,
    collected_by varchar(180),
    constraint fk_pickups_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_pickups_market foreign key (market_id) references markets(id),
    constraint fk_pickups_store foreign key (store_id) references stores(id),
    constraint fk_pickups_sale foreign key (linked_sale_id) references sales(id)
);

create index if not exists idx_pickups_tenant_market_status on pickups (tenant_id, market_id, status);
create index if not exists idx_pickups_store on pickups (store_id);
create index if not exists idx_pickups_sale on pickups (linked_sale_id);
