create table if not exists markets (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null,
    name varchar(180) not null,
    email varchar(180) not null,
    city varchar(120) not null,
    currency varchar(10) not null,
    uf_enabled boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    constraint fk_markets_tenant foreign key (tenant_id) references tenants (id),
    constraint uk_markets_tenant_name unique (tenant_id, name)
);

insert into markets (
    tenant_id,
    name,
    email,
    city,
    currency,
    uf_enabled,
    created_at,
    updated_at,
    created_by,
    updated_by
)
select
    t.id,
    concat(t.name, ' Market'),
    concat(t.code, '@market.local'),
    'Santiago',
    'CLP',
    true,
    current_timestamp,
    current_timestamp,
    'flyway',
    'flyway'
from tenants t
where not exists (
    select 1
    from markets m
    where m.tenant_id = t.id
);

alter table stores add column if not exists market_id bigint;

update stores s
set market_id = (
    select m.id
    from markets m
    where m.tenant_id = s.tenant_id
    order by m.id
    fetch first 1 row only
)
where s.market_id is null;

alter table stores alter column market_id set not null;
alter table stores add constraint fk_stores_market foreign key (market_id) references markets (id);

alter table sales add column if not exists market_id bigint;

update sales s
set market_id = (
    select st.market_id
    from sale_items si
    join stores st on st.id = si.store_id
    where si.sale_id = s.id
    order by si.id
    fetch first 1 row only
)
where s.market_id is null;

update sales s
set market_id = (
    select m.id
    from markets m
    where m.tenant_id = s.tenant_id
    order by m.id
    fetch first 1 row only
)
where s.market_id is null
  and s.status <> 'OPEN';

alter table sales add constraint fk_sales_market foreign key (market_id) references markets (id);

create index if not exists idx_markets_tenant on markets (tenant_id);
create index if not exists idx_stores_market on stores (market_id);
create index if not exists idx_sales_market on sales (market_id);
