create table daily_closings (
    id bigint generated by default as identity primary key,
    market_id bigint not null,
    closing_date date not null,
    sale_count bigint not null,
    total_sales_amount numeric(19,4) not null,
    total_commission_amount numeric(19,4) not null,
    total_net_amount numeric(19,4) not null,
    closed_at timestamp with time zone not null,
    closed_by varchar(120) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    constraint uk_daily_closings_market_date unique (market_id, closing_date),
    constraint fk_daily_closings_market foreign key (market_id) references markets (id)
);

create index idx_daily_closings_market_date on daily_closings (market_id, closing_date);

create table daily_closing_stores (
    id bigint generated by default as identity primary key,
    daily_closing_id bigint not null,
    store_id bigint not null,
    store_name_snapshot varchar(180) not null,
    sale_count bigint not null,
    total_sales_amount numeric(19,4) not null,
    total_commission_amount numeric(19,4) not null,
    total_net_amount numeric(19,4) not null,
    total_items bigint not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(120) not null,
    updated_by varchar(120) not null,
    constraint fk_daily_closing_stores_closing foreign key (daily_closing_id) references daily_closings (id),
    constraint fk_daily_closing_stores_store foreign key (store_id) references stores (id)
);

create index idx_daily_closing_stores_closing on daily_closing_stores (daily_closing_id);
create index idx_daily_closing_stores_store on daily_closing_stores (store_id);
