create table if not exists users (
    id bigint generated by default as identity primary key,
    email varchar(180) not null unique,
    full_name varchar(180) not null,
    auth_provider varchar(40) not null,
    provider_subject varchar(180),
    active boolean not null default true,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists user_roles (
    user_id bigint not null,
    role_id bigint not null,
    constraint fk_user_roles_user foreign key (user_id) references users (id),
    constraint fk_user_roles_role foreign key (role_id) references roles (id),
    constraint uk_user_roles unique (user_id, role_id)
);

create table if not exists user_market_access (
    user_id bigint not null,
    market_id bigint not null,
    constraint fk_user_market_access_user foreign key (user_id) references users (id),
    constraint fk_user_market_access_market foreign key (market_id) references markets (id),
    constraint uk_user_market_access unique (user_id, market_id)
);

create table if not exists user_store_access (
    user_id bigint not null,
    store_id bigint not null,
    constraint fk_user_store_access_user foreign key (user_id) references users (id),
    constraint fk_user_store_access_store foreign key (store_id) references stores (id),
    constraint uk_user_store_access unique (user_id, store_id)
);

insert into roles (code, name, created_at, updated_at, created_by, updated_by)
select 'ADMIN_SYSTEM', 'Administrador sistema', current_timestamp, current_timestamp, 'system', 'system'
where not exists (select 1 from roles where code = 'ADMIN_SYSTEM');

insert into roles (code, name, created_at, updated_at, created_by, updated_by)
select 'ADMIN_MARKET', 'Administrador mercado', current_timestamp, current_timestamp, 'system', 'system'
where not exists (select 1 from roles where code = 'ADMIN_MARKET');

insert into roles (code, name, created_at, updated_at, created_by, updated_by)
select 'COLLABORATOR', 'Colaborador', current_timestamp, current_timestamp, 'system', 'system'
where not exists (select 1 from roles where code = 'COLLABORATOR');

insert into roles (code, name, created_at, updated_at, created_by, updated_by)
select 'STORE_USER', 'Usuario tienda', current_timestamp, current_timestamp, 'system', 'system'
where not exists (select 1 from roles where code = 'STORE_USER');

insert into users (email, full_name, auth_provider, provider_subject, active, last_login_at, created_at, updated_at)
select
    au.email,
    au.full_name,
    'GOOGLE',
    au.google_subject,
    au.active,
    null,
    au.created_at,
    au.updated_at
from app_users au
where not exists (
    select 1
    from users u
    where lower(u.email) = lower(au.email)
);

insert into user_roles (user_id, role_id)
select u.id, au.role_id
from app_users au
join users u on lower(u.email) = lower(au.email)
where not exists (
    select 1
    from user_roles ur
    where ur.user_id = u.id and ur.role_id = au.role_id
);

insert into user_store_access (user_id, store_id)
select u.id, su.store_id
from store_users su
join app_users au on au.id = su.user_id
join users u on lower(u.email) = lower(au.email)
where su.active = true
  and not exists (
      select 1
      from user_store_access usa
      where usa.user_id = u.id and usa.store_id = su.store_id
  );

create index if not exists idx_users_email on users (email);
create index if not exists idx_user_roles_user on user_roles (user_id);
create index if not exists idx_user_market_access_user on user_market_access (user_id);
create index if not exists idx_user_store_access_user on user_store_access (user_id);
